<a href="https://colab.research.google.com/github/Akshat5129/AI-ADV-AU/blob/main/Assignment_3_AU19B1023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt, re
import nltk

In [ ]:
df_spam = pd.read_csv('./downloads/SpamCollection',sep='\t',header=None,names=['review','label'])
df_spam.head(20)

review                                              label
0     ham  Go until jurong point, crazy.. Available only ...
1     ham                      Ok lar... Joking wif u oni...
2    spam  Free entry in 2 a wkly comp to win FA Cup fina...
3     ham  U dun say so early hor... U c already then say...
4     ham  Nah I don't think he goes to usf, he lives aro...
5    spam  FreeMsg Hey there darling it's been 3 week's n...
6     ham  Even my brother is not like to speak with me. ...
7     ham  As per your request 'Melle Melle (Oru Minnamin...
8    spam  WINNER!! As a valued network customer you have...
9    spam  Had your mobile 11 months or more? U R entitle...
10    ham  I'm gonna be home soon and i don't want to tal...
11   spam  SIX chances to win CASH! From 100 to 20,000 po...
12   spam  URGENT! You have won a 1 week FREE membership ...
13    ham  I've been searching for the right words to tha...
14    ham                I HAVE A DATE ON SUNDAY WITH WILL!!
15   spam  XXXMobileMovieClub: To use your credit, click ...
16    ham                         Oh k...i'm watching here:)
17    ham  Eh u remember how 2 spell his name... Yes i di...
18    ham  Fine if that’s the way u feel. That’s the way ...
19   spam  England v Macedonia - dont miss the goals/team...

In [ ]:
import nlp_tools
import contractions

In [ ]:
text = df_spam['label'][0]
text

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [ ]:
#nlp_tools.lemmatization_sentence(text)
nlp_tools.lemmatization_sentence(text)

'go until jurong point crazy .. available only in bugis n great world la e buffet ... cine there get amore wat ...'

In [ ]:
txt = "i don't like mail spam"
contractions.expand_contraction(txt)

'i do not like mail spam'

In [ ]:
df_spam['clean_label'] = df_spam['label'].apply(contractions.expand_contraction)
df_spam['clean_label'] = df_spam['clean_label'].apply(nlp_tools.lemmatization_sentence)

In [ ]:
df_spam.head()

review                                              label  \
0    ham  Go until jurong point, crazy.. Available only ...   
1    ham                      Ok lar... Joking wif u oni...   
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3    ham  U dun say so early hor... U c already then say...   
4    ham  Nah I don't think he goes to usf, he lives aro...   

                                         clean_label  
0  go until jurong point crazy .. available only ...  
1                      ok lar ... joke wif u oni ...  
2  free entry in 2 a wkly comp to win fa cup fina...  
3  u dun say so early hor ... u c already then sa...  
4  nah i do not think he go to usf he live around...

In [ ]:
df_spam['clean_label'].ndim

1

In [ ]:
### Word Embedding
 #bag of words

In [ ]:
label_list = df_spam['clean_label'].tolist()

In [ ]:
print(review_list)

['go until jurong point crazy .. available only in bugis n great world la e buffet ... cine there get amore wat ...', 'ok lar ... joke wif u oni ...', "free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005. text fa to 87121 to receive entry question std txt rate t c 's apply 08452810075over18 's", 'u dun say so early hor ... u c already then say ...', 'nah i do not think he go to usf he live around here though', "freemsg hey there darling it be be 3 week 's now and no word back i would like some fun you up for it still tb ok xxx std chgs to send £1.50 to rcv", 'even my brother be not like to speak with me they treat me like aid patent', "a per your request 'melle melle oru minnaminunginte nurungu vettam have be set a your callertune for all caller press 9 to copy your friend callertune", 'winner a a value network customer you have be select to receivea £900 prize reward to claim call 09061701461. claim code kl341 valid 12 hour only', 'have your mobile 11 month or more u r 

In [ ]:
type(review_list)

list

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv= CountVectorizer()

In [ ]:
cv.fit(label_list) # all unique words in a array

CountVectorizer()

In [ ]:
X = cv.transform(label_list).toarray()

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
type(X)

numpy.ndarray

In [ ]:
len(cv.get_feature_names())

7753

In [ ]:
y = df_spam['review'].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(x_train,y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn import metrics

In [ ]:
cr = metrics.classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

         ham       0.99      0.99      0.99      1181
        spam       0.95      0.94      0.94       212

    accuracy                           0.98      1393
   macro avg       0.97      0.96      0.97      1393
weighted avg       0.98      0.98      0.98      1393



In [ ]:
test_text ="The Document preview is currently being processed. Please try again later."

In [ ]:
 #step-1: contraction
clean_text = contractions.expand_contraction(test_text)
#step-2: lemma
lema_text = nlp_tools.lemmatization_sentence(clean_text)
# step-3: bag of words
vector = cv.transform([lema_text]).toarray()
# step-4: machine learning model
res = model.predict(vector)
prob = model.predict_proba(vector)

In [ ]:
res

array(['ham'], dtype='<U4')

In [ ]:
prob

array([[0.9984308, 0.0015692]])

In [ ]:
X[:3,:]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
df_spammmmm = pd.DataFrame(X,columns=cv.get_feature_names())

In [ ]:
df_spammmmm

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0      0    0       0             0     0     0            0            0   
1      0    0       0             0     0     0            0            0   
2      0    0       0             0     0     0            0            0   
3      0    0       0             0     0     0            0            0   
4      0    0       0             0     0     0            0            0   
...   ..  ...     ...           ...   ...   ...          ...          ...   
5567   0    0       0             0     0     0            0            0   
5568   0    0       0             0     0     0            0            0   
5569   0    0       0             0     0     0            0            0   
5570   0    0       0             0     0     0            0            0   
5571   0    0       0             0     0     0            0            0   

      0125698789  02  ...  zhong  zindgi  zoe  zogtorius  zoom  zouk  zyada  \
0              0   0  ...      0       0    0          0     0     0      0   
1              0   0  ...      0       0    0          0     0     0      0   
2              0   0  ...      0       0    0          0     0     0      0   
3              0   0  ...      0       0    0          0     0     0      0   
4              0   0  ...      0       0    0          0     0     0      0   
...          ...  ..  ...    ...     ...  ...        ...   ...   ...    ...   
5567           0   0  ...      0       0    0          0     0     0      0   
5568           0   0  ...      0       0    0          0     0     0      0   
5569           0   0  ...      0       0    0          0     0     0      0   
5570           0   0  ...      0       0    0          0     0     0      0   
5571           0   0  ...      0       0    0          0     0     0      0   

      èn  ú1  〨ud  
0      0   0    0  
1      0   0    0  
2      0   0    0  
3      0   0    0  
4      0   0    0  
...   ..  ..  ...  
5567   0   0    0  
5568   0   0    0  
5569   0   0    0  
5570   0   0    0  
5571   0   0    0  

[5572 rows x 7753 columns]